import { Link } from 'react-router-dom';
export default function HomePage() {
    return <main className="home-page">
        <section className="home-hero"><div className="hero-copy"><p className="eyebrow"><span /> HEALTHCARE, WITH ROOM TO BREATHE</p><h1>Good care starts<br />with a <em>connection.</em></h1><p className="hero-description">A simpler way to find a doctor, book your next appointment and stay connected to your care.</p><div className="hero-actions"><Link to="/doctors" className="premium-button">Find a doctor <i className="bi bi-arrow-up-right" aria-hidden="true" /></Link><Link to="/register" className="text-action">Create your account <i className="bi bi-arrow-right" aria-hidden="true" /></Link></div><div className="hero-detail"><span><i className="bi bi-patch-check" aria-hidden="true" /> Reviewed doctor credentials</span><span><i className="bi bi-calendar2-check" aria-hidden="true" /> Book available times</span></div></div><div className="hero-art" aria-hidden="true"><div className="hero-art-grid" /><span className="hero-art-label">A BETTER CONNECTION</span><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-symbol">+</div><span className="hero-art-bottom">People first.<br />Always.</span></div></section>
        <section className="home-steps" aria-labelledby="care-steps"><div className="home-section-heading"><p className="eyebrow">FROM SEARCH TO CONSULTATION</p><h2 id="care-steps">Your next step, made simple.</h2></div><div className="home-step-grid">{[['01', 'Find your doctor', 'Browse doctors by speciality and choose the care that fits your needs.', '/doctors', 'Explore doctors'], ['02', 'Choose your time', 'See available consultation times and request an appointment.', '/doctors', 'Find an appointment'], ['03', 'Keep it all together', 'Follow confirmations and manage your upcoming visits in your account.', '/dashboard', 'Open your workspace']].map(([number, title, description, path, label]) => <article key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{description}</p><Link to={path}>{label} <i className="bi bi-arrow-right" aria-hidden="true" /></Link></article>)}</div></section>
        <section className="doctor-invitation"><div><p className="eyebrow">FOR HEALTHCARE PROFESSIONALS</p><h2>More time for your patients.</h2><p>Organise your consultation hours, manage appointments and keep your professional profile up to date.</p></div><Link to="/register" className="premium-button">Join as a doctor <i className="bi bi-arrow-up-right" aria-hidden="true" /></Link></section>
        <footer className="home-footer"><span className="auth-wordmark">sihatech</span><span>Care, connected.</span><span>© {new Date().getFullYear()} SihaTech</span></footer>
    </main>;
}
